# Generated by Django 4.1 on 2022-09-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_end_date'),
        ('polls', '0003_remove_choice_votes_alter_question_end_date_vote'),
    ]

    operations = [
    ]
